name: nasa
description: Galerias de nasa

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - img/nasa_icon.png
    
  fonts:
    - family: Quicksand
      fonts:
        - asset: font/Quicksand/Quicksand-Bold.ttf
        - asset: font/Quicksand/Quicksand-Light.ttf
        - asset: font/Quicksand/Quicksand-Medium.ttf
        - asset: font/Quicksand/Quicksand-Regular.ttf
        - asset: font/Quicksand/Quicksand-SemiBold.ttf
 